### ISSUE TITLE
Add OG tags

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website-v2#61]
For better social media sharing.

**Comment by watzon** [comment]
I was going to put this here if it wasn't already. This would be very handy and wouldn't require an immense amount of effort.

**Comment by paulcsmith** [comment]
Could you share a bit more about what these are and what it would look like to implement? I'm totally unfamiliar with OG tags

**Comment by jwoertink** [comment]
They're meta tags that just tell social media sites how to display certain info. Like What image to show, what title to display and such. 

`meta name: "og:title", value: "Saving Form"`

**Comment by watzon** [comment]
You can check here for more info http://ogp.me/

**Comment by paulcsmith** [comment]
Ahh. Cool :D I was wondering what OG stood for. Thanks :D

**Comment by watzon** [comment]
It's just a nice bit of metadata that makes sharing easier. For instance, I wanted to share the new site on telegram the other day and usually telegram will go fetch an image and a description and show the link as a card of sorts, but for luckyframework.org it was just a plane ol' link.
