### ISSUE TITLE
Get our site grade up

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website-v2#68]
https://website.grader.com/results/www.luckyframework.org

Right now we score a 45/100, but there's no reason we can't be at 100/100. It's actually pretty simple with just a few small things. We want to ensure that Lucky ranks well in searches. A few extra meta tags should help out.

**Comment by paulcsmith** [comment]
Thanks for posting! This gives some great ideas

I'd love to get that perf score to 30/30 especially :D Hehe Just needs to compress the JS/CSS I think. Maybe there is a GzipHandler for Crystal that we can use.

**Comment by jwoertink** [comment]
Turns out their [grader is broke](https://twitter.com/jeremywoertink/status/1143292953126821888) but we also these:

* https://www.woorank.com/en/www/luckyframework.org
* https://seositecheckup.com/seo-audit/luckyframework.org
* https://validator.w3.org/

I've started working on this, so I'll be able to use all of these together to really make sure everything is covered.

**Comment by paulcsmith** [comment]
Another good one for performance https://developers.google.com/speed/pagespeed/insights/?url=luckyframework.org

**Comment by paulcsmith** [comment]
I feel a lot of these tools are wrong though because in the screenshots of page speed the website is visible almost instantly but it doesn't think it is ready until 7s in...so I dunno. Still some good ideas on there regardless

**Comment by jwoertink** [comment]
This could be caused from [this](https://github.com/luckyframework/website-v2/blob/master/src/components/shared/layout_head.cr#L15) not being deferred. I can add that on in my PR, I just wasn't sure how that script works and if deferring it would make a difference.
